version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: imperium-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: imperiumdb
      MYSQL_USER: imperium
      MYSQL_PASSWORD: imperium
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "imperium", "-pimperium"]
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 5s

  backend:
    build:
      context: ./ImperiumBack/sourses
      dockerfile: Imperium.Web/Dockerfile
    container_name: imperium-back
    ports:
      - "5000:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__DefaultConnection: "Server=db;Port=3306;Database=imperiumdb;Uid=imperium;Pwd=imperium"
    restart: always

  liquibase:
    image: liquibase/liquibase
    container_name: liquibase-runner
    volumes:
      - ./ImperiumBack/database:/workspace
    working_dir: /workspace
    depends_on:
      db:
        condition: service_healthy
    command:
      [
        "--url=jdbc:mysql://db:3306/imperiumdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&connectTimeout=60000&socketTimeout=60000",
        "--username=imperium",
        "--password=imperium", 
        "--driver=com.mysql.cj.jdbc.Driver",
        "--classpath=driver/mysql-connector-java-8.0.33.jar",
        "--changelog-file=changelog/0-db.changelog-master.xml",
        "update"
      ]
    restart: "no"

volumes:
  mysql_data: